
language: cpp

matrix:
  include:
    - compiler: gcc
      os: linux
      script: ./.ci/linux-gl.sh
      before_install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
        - sudo apt-get update
        - sudo apt-get install python3 -y
        - sudo apt-get install libglew-dev -y
        - sudo apt-get install gcc-7 g++-7 -y
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 60
    - compiler: clang
      os: osx
      script: ./.ci/mac-gl.sh
    - language: glsl
      os: osx
      script: ./.ci/glsl-shaders.sh
